-- =========================================================
-- BuildTrack Sample Data
-- Construction Project Management & Site Monitoring Platform
-- Database: PostgreSQL
-- Version: 1.0
-- =========================================================

SET search_path TO buildtrack;

-- =========================================================
-- SAMPLE DATA: Roles
-- =========================================================

INSERT INTO roles (role_name, description)
VALUES
('Administrator', 'Has complete access to the BuildTrack platform.'),
('Project Manager', 'Responsible for planning and managing construction projects.'),
('Site Engineer', 'Monitors construction activities and submits progress reports.'),
('Worker', 'Construction workforce assigned to projects.'),
('Client', 'Represents the customer for whom the construction project is executed.');

-- =========================================================
-- SAMPLE DATA: Company
-- =========================================================

INSERT INTO companies
(
    company_name,
    company_code,
    company_email,
    company_phone,
    address
)
VALUES
(
    'ABC Builders',
    'ABC001',
    'contact@abcbuilders.com',
    '9876543210',
    'Visakhapatnam, Andhra Pradesh'
);

-- =========================================================
-- SAMPLE DATA: Users
-- Password (for all users):
-- Replace with the BCrypt hash generated by your backend.
-- =========================================================

INSERT INTO users
(
    company_id,
    role_id,
    full_name,
    email,
    password_hash,
    phone_number
)
VALUES
(
    (SELECT company_id FROM companies WHERE company_code = 'ABC001'),
    (SELECT role_id FROM roles WHERE role_name = 'Administrator'),
    'System Administrator',
    'admin@buildtrack.com',
    '$2b$12$REPLACE_WITH_BCRYPT_HASH',
    '9876543211'
),
(
    (SELECT company_id FROM companies WHERE company_code = 'ABC001'),
    (SELECT role_id FROM roles WHERE role_name = 'Project Manager'),
    'Rahul Sharma',
    'pm@buildtrack.com',
    '$2b$12$REPLACE_WITH_BCRYPT_HASH',
    '9876543212'
),
(
    (SELECT company_id FROM companies WHERE company_code = 'ABC001'),
    (SELECT role_id FROM roles WHERE role_name = 'Site Engineer'),
    'Priya Reddy',
    'engineer@buildtrack.com',
    '$2b$12$REPLACE_WITH_BCRYPT_HASH',
    '9876543213'
),
(
    (SELECT company_id FROM companies WHERE company_code = 'ABC001'),
    (SELECT role_id FROM roles WHERE role_name = 'Worker'),
    'Arjun Kumar',
    'worker@buildtrack.com',
    '$2b$12$REPLACE_WITH_BCRYPT_HASH',
    '9876543214'
),
(
    (SELECT company_id FROM companies WHERE company_code = 'ABC001'),
    (SELECT role_id FROM roles WHERE role_name = 'Client'),
    'Rajesh Kumar',
    'client@buildtrack.com',
    '$2b$12$REPLACE_WITH_BCRYPT_HASH',
    '9876543215'
);

-- =========================================================
-- VERIFY SAMPLE DATA
-- =========================================================

SELECT * FROM roles;
SELECT company_id, company_name FROM companies;
SELECT user_id, full_name, email, role_id FROM users;

-- =========================================================
-- Sample Data Loaded Successfully
-- =========================================================

SELECT 'BuildTrack sample data inserted successfully.' AS status;

SELECT * FROM buildtrack.project_categories;

SELECT company_id, company_name FROM buildtrack.companies;

SELECT user_id, full_name, role_id FROM buildtrack.users;

SELECT category_id, category_name FROM buildtrack.project_categories;

SELECT status_id, status_name FROM buildtrack.project_statuses;

SELECT * FROM buildtrack.roles;